package com.jimi.mes_dbcopier.model;

import com.jimi.mes_dbcopier.model.base.BaseBackupLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BackupLog extends BaseBackupLog<BackupLog> {
	public static final BackupLog dao = new BackupLog().dao();
}
