package com.jimi.mes_dbcopier.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBackupLog<M extends BaseBackupLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setBackupTime(java.util.Date backupTime) {
		set("backup_time", backupTime);
		return (M)this;
	}
	
	public java.util.Date getBackupTime() {
		return get("backup_time");
	}

	public M setNumber(java.lang.Long number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Long getNumber() {
		return getLong("number");
	}

	public M setTable(java.lang.String table) {
		set("table", table);
		return (M)this;
	}
	
	public java.lang.String getTable() {
		return getStr("table");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setConsumeTime(java.lang.Integer consumeTime) {
		set("consume_time", consumeTime);
		return (M)this;
	}
	
	public java.lang.Integer getConsumeTime() {
		return getInt("consume_time");
	}

}
